### ISSUE TITLE
Unknown plugin "transform-runtime" 

### ISSUE THREAD

**Issue by richstandbrook** [songyazhao/vue-plain-slider#1]
In the browser I get this:

```
Uncaught Error: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/richard/Sites/X/Y/node_modules/vue-plain-slider/.babelrc" at 0, attempted to resolve relative to "/Users/richard/Sites/X/Y/node_modules/vue-plain-slider"
```

Looks like the module specifies `transform-runtime` as a babel plugin, but not a dependancy?

**Comment by DestinyHunter** [comment]
You can try installing babel-plugin-transform-runtime

     npm install --save-dev babel-plugin-transform-runtime

edit  .babelrc

      {
        "plugins": ["transform-runtime"]
       }

**Comment by songyazhao** [comment]
@richstandbrook 
Problem has been repaired
Please update version **1.0.2**
Or delete that file `node_modules/vue-plain-slider/.babelrc`
