### ISSUE TITLE
Less

### ISSUE THREAD

**Issue by EdwinHauspie** [songyazhao/vue-plain-slider#2]
The page states that it is lightweight and has **no dependencies**, however I need to install a less loader in my project just for this one component.

It literally has 20 lines of css, so maybe a plain css file would be fine too.

**Comment by songyazhao** [comment]
@UsernamesAreOutdated 
Thanks for your suggestions, the next version of the release, I will use build after of code, namely `.css` file.

**Comment by songyazhao** [comment]
Please update to version 1.1.0
