### ISSUE TITLE
slider里的div不可以用循环遍历出来吗

### ISSUE THREAD

**Issue by show-console** [songyazhao/vue-plain-slider#7]
我用v-for遍历slider里的div时，翻页功能就不能用了，无法正常翻到第二页

**Comment by songyazhao** [comment]
可以的，可以看下 [src/views/Demo/Full.vue](https://github.com/songyazhao/vue-plain-slider/blob/d7e455d1af17d923f6f392b6c0d40b334337f81b/src/views/Demo/Full.vue#L30)
